# Generated by Django 4.0.4 on 2022-09-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_your_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='your_description',
            field=models.TextField(blank=True, default="What's up?", max_length=150),
        ),
    ]
