# Generated by Django 4.0.4 on 2022-08-24 10:40

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_pages',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='book_genre',
            field=models.ForeignKey(default=products.models.get_default_book_genre, on_delete=django.db.models.deletion.DO_NOTHING, to='products.bookgenre'),
        ),
    ]
