# Generated by Django 4.0.4 on 2022-09-01 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_bookgenre_product_number_of_pages_product_book_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_age', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='BookMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_mood', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='book_age',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.bookage'),
        ),
        migrations.AddField(
            model_name='product',
            name='book_mood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.bookmood'),
        ),
    ]
